---
title: "Sampling Demostration from Class"
author: "Jessica Edwards and Michael Wu"
date: "3/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(googlesheets4)
library(fs)
library(janitor)
library(ggthemes)
library(moderndive)
library(infer)

sheets_deauth()

sampling_data <- read_sheet('https://docs.google.com/spreadsheets/d/14HmwN2cEVAJHupuehCuLdwG9BXtR3COrxDgaaylLhkA/edit?usp=sharing') %>%
  clean_names()
```

```{r create-table, echo = FALSE}
sampling_data <- sampling_data %>%
  slice(1:51) %>%
  mutate(percent_red = red/(red+white))

x <- ggplot(sampling_data, aes(x = percent_red)) +
  geom_histogram(bins = 20) +
  labs(
    title = "Percentage of Red Beads Drawn",
    subtitle = "Should we be suspicious of the outliers?",
    caption = "Classroom data from 2020-03-03",
    x = "Percent Red Beads",
    y = "Count"
  ) +
  theme_classic()

# Urn 1 from the textbook implementation using moderndive

urn1 <- bowl %>% 
  rep_sample_n(size = 25, reps = 50) %>%
  group_by(replicate) 

# Urn 2 from class implementation

urn2 <- tibble(color = c(rep("Red", 2000), rep("White", 8000))) 

simulate_class <- function(urn) {
  urn %>%
    rep_sample_n(size = 25, reps = 51) %>%
    group_by(replicate) %>%
    summarize(red = sum(color == "Red")) %>% 
    mutate(prop_red = red / 25)
}

sim_results <- tibble(sim_ID = 1:1000,
                      results = map(sim_ID, ~ simulate_class(urn2)))


# urn2_plot <- ggplot(urn2, aes(x = prop_red)) +
#   geom_histogram(bins = 10) +
#   theme_classic() + 
#   labs(title = "Distribution of Red Beads", subtitle = "51 Simulations", x = "Proportion of Red Beads", y = "Count")
# 
# urn2_plot

sim_results[[2]][[2]] %>%
  ggplot(aes(x = prop_red)) +
  geom_histogram(bins = 20) +
  theme_classic()
```


